# Generated by Django 4.1 on 2023-06-05 06:39

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacao',
            name='cpf_representante',
            field=sloth.db.models.BrCpfField(blank=True, max_length=255, null=True, verbose_name='CPF do Representante'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='foto_boletim_ocorrencia',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto do Boletim de Ocorrência'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='foto_chassi_veiculo',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto do Chassi do Veículo'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='foto_descarte_placa_dianteira',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto do Descarte da Placa Dianteira'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='foto_descarte_placa_traseira',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto do Descarte da Placa Traseira'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='foto_descarte_segunda_placa_traseira',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto do Descarte da Segunda Placa Traseira'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='foto_dianteira_veiculo',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto Dianteira do Veículo'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='foto_documento_proprietario',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto do Documento do Proprietário'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='foto_documento_representante',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto do Documento do Representante'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='foto_perfil_proprietario',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto de Perfil do Proprietário'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='foto_perfil_representante',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto de Perfil do Representante'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='foto_placa_dianteira',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto da Placa Dianteira'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='foto_placa_traseira',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto da Placa Traseira'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='foto_procuracao',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto da Procuração'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='foto_segunda_placa_traseira',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto da Segunda Placa Traseira'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='foto_traseira_veiculo',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto Traseira do Veículo'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='nome_proprietario',
            field=sloth.db.models.CharField(max_length=255, verbose_name='Nome do Proprietário'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='nome_representante',
            field=sloth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Representante'),
        ),
    ]
