# Generated by Django 4.1 on 2023-06-08 18:36

from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0005_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', sloth.db.models.CharField(max_length=255, verbose_name='Descrição')),
                ('satisfeita', models.BooleanField(null=True, verbose_name='Satisfeita')),
                ('validacao', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='av.validacao', verbose_name='Validação')),
            ],
            options={
                'verbose_name': 'Verificação',
                'verbose_name_plural': 'Verificações',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
