# Generated by Django 4.1 on 2023-06-09 00:41

from django.db import migrations, models
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0006_verificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='observacao',
        ),
        migrations.AddField(
            model_name='consulta',
            name='valida',
            field=models.BooleanField(default=True, verbose_name='Válida'),
        ),
        migrations.AddField(
            model_name='verificacao',
            name='observacao',
            field=sloth.db.models.CharField(max_length=255, null=True, verbose_name='Observação'),
        ),
    ]
