# Generated by Django 4.1 on 2023-06-09 06:31

from django.db import migrations, models
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0007_remove_consulta_observacao_consulta_valida_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
        migrations.CreateModel(
            name='CodigoCor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('cores', sloth.db.models.ManyToManyField(blank=True, to='av.cor', verbose_name='Cores')),
            ],
            options={
                'verbose_name': 'Código de Cor',
                'verbose_name_plural': 'Códigos de Cores',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
