# Generated by Django 4.1 on 2023-06-09 07:26

from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0008_alter_cor_options_codigocor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estampador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', sloth.db.models.BrCnpjField(max_length=255, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Estampador',
                'verbose_name_plural': 'Estampadores',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.AddField(
            model_name='consulta',
            name='url',
            field=sloth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='valor',
            field=sloth.db.models.TextField(verbose_name='Valor'),
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', sloth.db.models.BrCpfField(max_length=255, verbose_name='CPF')),
                ('foto', sloth.db.models.PhotoField(upload_to='operadores', verbose_name='Foto')),
                ('estampador', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='av.estampador', verbose_name='Estampador')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='LocalInstalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', sloth.db.models.CharField(max_length=255, verbose_name='Latitude')),
                ('longitude', sloth.db.models.CharField(max_length=255, verbose_name='Longitude')),
                ('estampador', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='av.estampador', verbose_name='Estampador')),
            ],
            options={
                'verbose_name': 'Local de Instalação',
                'verbose_name_plural': 'Locais de Instalação',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
