# Generated by Django 4.1 on 2023-06-09 07:33

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0009_estampador_consulta_url_alter_consulta_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localinstalacao',
            name='nome',
            field=sloth.db.models.CharField(default=None, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
