# Generated by Django 4.1 on 2023-06-09 07:43

from django.db import migrations
import django.db.models.deletion
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0010_localinstalacao_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validacao',
            name='dianteira',
        ),
        migrations.RemoveField(
            model_name='validacao',
            name='segunda_traseira',
        ),
        migrations.RemoveField(
            model_name='validacao',
            name='traseira',
        ),
        migrations.AddField(
            model_name='validacao',
            name='estampador',
            field=sloth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='av.estampador', verbose_name='Estampador'),
        ),
        migrations.AddField(
            model_name='validacao',
            name='latitude',
            field=sloth.db.models.CharField(max_length=255, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='validacao',
            name='longitude',
            field=sloth.db.models.CharField(max_length=255, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='validacao',
            name='operador',
            field=sloth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='av.operador', verbose_name='Operador'),
        ),
    ]
