# Generated by Django 4.1 on 2023-06-09 07:52

from django.db import migrations
import django.db.models.deletion
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0011_remove_validacao_dianteira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacao',
            name='local',
            field=sloth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='av.localinstalacao', verbose_name='Local'),
        ),
    ]
