# Generated by Django 4.1 on 2023-06-09 09:06

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0013_remove_validacao_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacao',
            name='foto_perfil_operador',
            field=sloth.db.models.PhotoField(null=True, upload_to='', verbose_name='Foto de Perfil do Operador'),
        ),
    ]
