# Generated by Django 4.1 on 2023-06-09 09:27

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0014_validacao_foto_perfil_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='foto',
            field=sloth.db.models.PhotoField(upload_to='fotos', verbose_name='Foto'),
        ),
    ]
