# Generated by Django 4.1 on 2023-06-21 08:34

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0017_consultaavulso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaavulso',
            name='resultado',
            field=sloth.db.models.TextField(blank=True, null=True, verbose_name='Resultado'),
        ),
    ]
