# Generated by Django 4.1 on 2023-06-27 06:37

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0018_alter_consultaavulso_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacao',
            name='foto_documento_proprietario_2',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto do Documento do Proprietário 2'),
        ),
        migrations.AddField(
            model_name='validacao',
            name='foto_documento_representante_2',
            field=sloth.db.models.PhotoField(blank=True, null=True, upload_to='fotos', verbose_name='Foto do Documento do Representante 2'),
        ),
    ]
